version: "3"

services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - '3000:8080'
    depends_on:
      - backend
    

  backend:
    container_name: backend
    build: ./mysite
    ports:
      - '8001:8000'