version: "3"

services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - '3000:8080'
    volumes:
      - ./frontend/app:/app/ 
    depends_on:
      - backend
    

  backend:
    container_name: backend
    build: ./mysite
    ports:
      - '8001:8000'
    environment:
      - ENV=prod
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=what2do
